### ISSUE TITLE
`node.set` is deprecated and will be removed in Chef 14

### ISSUE THREAD

**Issue by grv87** [grv87/cmake-cookbook#3]
```
    UbuntuServer16.04.2_amd64: [2017-05-19T15:02:48+00:00] WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) (CHEF-4)/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/cmake/recipes/_binary.rb:28:in `block (2 levels) in from_file'.
    UbuntuServer16.04.2_amd64: Please see https://docs.chef.io/deprecations_attributes.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
    UbuntuServer16.04.2_amd64: [2017-05-19T15:02:48+00:00] WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) (CHEF-4)/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/cmake/recipes/_binary.rb:30:in `block (2 levels) in from_file'.
    UbuntuServer16.04.2_amd64: Please see https://docs.chef.io/deprecations_attributes.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
```

**Comment by grv87** [comment]
```
node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at 1 location:
           - /tmp/kitchen/cache/cookbooks/cmake/recipes/_binary.rb:30:in `block (2 levels) in from_file'
          See https://docs.chef.io/deprecations_attributes.html for further details.
```
